import React,{useState,useEffect} from 'react';
import {api,HealthAPI} from '../../shared/lib/api.js';
import {useApiData} from '../lib/useApiData.js';
import {Card,ErrorState} from '../../shared/components/ui.jsx';
import {healthAvailability,readDeviceHealth,HEALTH_TYPES} from '../../shared/lib/deviceHealth.js';
import {setReminders,registerPush} from '../../shared/lib/reminders.js';
export default function ConnectionsPage(){const provider=useApiData(()=>api('/api/integrations/inbody'),[]),[availability,setAvailability]=useState(null),[types,setTypes]=useState([]),[samples,setSamples]=useState([]),[message,setMessage]=useState(''),[hour,setHour]=useState(19),[busy,setBusy]=useState(false);
useEffect(()=>{healthAvailability().then(setAvailability).catch(()=>setAvailability({available:false,status:'error'}));},[]);
async function run(fn){setBusy(true);try{await fn();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
return <><Card title="InBody 연동"><p>{provider.data?.message||'연결 상태 확인 중…'}</p><p>상태: {provider.data?.status||'—'} · 마지막 성공: {provider.data?.last_sync_time||'없음'}</p>{provider.error&&<ErrorState message={provider.error.message} onRetry={provider.reload}/>}<button className="btn btn-ghost" disabled={busy} onClick={()=>run(()=>api('/api/integrations/inbody/sync',{}))}>동기화 확인</button></Card><Card title="Apple HealthKit · Android Health Connect"><p>{availability?.provider} · {availability?.available?'사용 가능':'미연결 / 현재 환경 미지원'}</p><p>선택한 항목의 읽기 권한만 요청합니다. 불러온 데이터는 이 화면에서만 표시하며 서버로 전송하지 않습니다.</p><div className="profile-grid">{HEALTH_TYPES.map(t=><label key={t}><input type="checkbox" checked={types.includes(t)} onChange={e=>setTypes(e.target.checked?[...types,t]:types.filter(v=>v!==t))}/>{t}</label>)}</div><button className="btn btn-primary" disabled={busy||!availability?.available||!types.length} onClick={()=>run(async()=>{const r=await readDeviceHealth(types,new Date(Date.now()-7*86400000).toISOString(),new Date().toISOString());setSamples(r.samples);setMessage(r.status);})}>권한 요청 · 최근 7일 읽기</button><p>불러온 기록 {samples.length}건 · 항목당 최근 최대 100건입니다. 중복·겹치는 기록을 합산하지 않습니다.</p>{samples.length>0&&<div className="data-table-wrap"><table><caption>기기에서 읽은 최근 기록 (처음 50건)</caption><thead><tr><th>항목</th><th>시작</th><th>값</th></tr></thead><tbody>{samples.slice(0,50).map((s,i)=><tr key={s.platformId||i}><td>{s.type}</td><td>{s.startDate}</td><td>{s.type==='workouts'?`${s.workoutType} · ${s.duration}초`:`${s.value} ${s.unit}`}</td></tr>)}</tbody></table></div>}</Card><Card title="운동 리마인더"><label>매일 알림 시각 <input type="number" min="0" max="23" value={hour} onChange={e=>setHour(Number(e.target.value))}/></label><div className="motion-controls"><button className="btn btn-primary" disabled={busy} onClick={()=>run(async()=>{const [measurements,routines,workouts]=await Promise.all([HealthAPI.listMeasurements(),HealthAPI.listRoutines(),HealthAPI.listWorkouts()]);await setReminders(true,{measurement:measurements.at(-1),routine:routines[0],workouts,hour});setMessage('기기 알림을 설정했습니다.');})}>로컬 알림 켜기</button><button className="btn btn-ghost" disabled={busy} onClick={()=>run(async()=>{await setReminders(false);setMessage('기기 알림을 해제했습니다.');})}>알림 해제</button><button className="btn btn-ghost" disabled={busy} onClick={()=>run(async()=>{await registerPush();setMessage('기기 푸시 등록 완료. 발송 서버는 별도로 연결해야 합니다.');})}>원격 푸시 연결 확인</button></div><p>알림에는 상세 건강수치를 포함하지 않습니다. 실제 발송 시간은 기기 절전·알림 설정에 영향을 받습니다.</p></Card><p role="status">{message}</p></>;}
