import {summarizeDeviceActivity} from '../lib/deviceActivity.js';
import React,{useState,useEffect} from 'react';
import {api,HealthAPI} from '../../shared/lib/api.js';
import {useApiData} from '../lib/useApiData.js';
import {Card,ErrorState} from '../../shared/components/ui.jsx';
import {healthAvailability,readDeviceHealth,HEALTH_TYPES} from '../../shared/lib/deviceHealth.js';
import {setReminders,registerPush} from '../../shared/lib/reminders.js';
export default function ConnectionsPage(){const provider=useApiData(()=>api('/api/integrations/inbody'),[]),[availability,setAvailability]=useState(null),[types,setTypes]=useState([]),[samples,setSamples]=useState([]),[message,setMessage]=useState(''),[hour,setHour]=useState(19),[busy,setBusy]=useState(false),[activityConsent,setActivityConsent]=useState(false);
const activity=activityConsent?summarizeDeviceActivity(samples):null;
useEffect(()=>{healthAvailability().then(setAvailability).catch(()=>setAvailability({available:false,status:'error'}));},[]);
async function run(fn){setBusy(true);try{await fn();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
return <><Card title="InBody 연동"><p>InBody 자동 연동은 지원 기관에서 사용할 수 있습니다. 수동 입력 또는 CSV 가져오기는 프로필에서 이용하세요.</p>{provider.data?.operational_state==='ERROR'&&<p role="alert">건강센터 데이터를 가져오지 못했습니다. 기존 기록은 계속 사용할 수 있습니다.</p>}<p>{provider.data?.message||'연결 상태 확인 중…'}</p><p>상태: {provider.data?.operational_state||provider.data?.status||'—'} · 최근 동기화: {provider.data?.last_sync_time||'없음'} · 최근 측정: {provider.data?.last_measurement_date||'없음'}</p>{provider.error&&<ErrorState message={provider.error.message} onRetry={provider.reload}/>}<button className="btn btn-ghost" disabled={busy||provider.data?.status==='not_connected'} onClick={()=>run(()=>api('/api/integrations/inbody/sync',{}))}>동기화 확인</button></Card><Card title="Apple HealthKit · Android Health Connect"><p>{availability?.provider} · {availability?.available?'사용 가능':'미연결 / 현재 환경 미지원'}</p><p>선택한 항목의 읽기 권한만 요청합니다. 불러온 데이터는 이 화면에서만 표시하며 서버로 전송하지 않습니다.</p><div className="profile-grid">{HEALTH_TYPES.map(t=><label key={t}><input type="checkbox" checked={types.includes(t)} onChange={e=>setTypes(e.target.checked?[...types,t]:types.filter(v=>v!==t))}/>{{steps:'걸음 수',workouts:'운동 시간',weight:'체중'}[t]}</label>)}</div><button className="btn btn-primary" disabled={busy||!availability?.available||!types.length} onClick={()=>run(async()=>{const r=await readDeviceHealth(types,new Date(Date.now()-7*86400000).toISOString(),new Date().toISOString());setSamples(r.samples);setMessage(r.status);})}>권한 요청 · 최근 7일 읽기</button><label><input type="checkbox" checked={activityConsent} onChange={e=>setActivityConsent(e.target.checked)}/>불러온 건강 기록을 이 화면의 일별 활동 추이에 반영하는 데 동의합니다.</label>
 {activity&&<section><h3>기기 건강 기록 · 일별 활동 추이</h3><p>최근 조회된 일부 표본 기준이며 하루 전체 합계가 아닙니다. 중복·겹침·날짜를 넘는 기록 {activity.excluded}건을 제외했습니다. 앱 운동 완료율에는 합산하지 않습니다.</p><div className="data-table-wrap"><table><caption>선택한 기기 건강 기록 (기기 현지 날짜)</caption><thead><tr><th>날짜</th><th>걸음 수</th><th>운동 분</th><th>마지막 체중 kg</th></tr></thead><tbody>{activity.days.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.stepSamples?d.steps:'미기록'}</td><td>{d.workoutSamples?Math.round(d.minutes):'미기록'}</td><td>{d.weight??'미기록'}</td></tr>)}</tbody></table></div><p>동의를 해제하면 추이를 숨깁니다. 화면을 나가면 불러온 자료와 동의 상태가 사라지며 서버에는 저장하지 않습니다.</p></section>}
 <p>불러온 기록 {samples.length}건 · 항목당 최근 최대 100건입니다. 중복·겹치는 기록을 합산하지 않습니다.</p>{samples.length>0&&<div className="data-table-wrap"><table><caption>기기에서 읽은 최근 기록 (처음 50건)</caption><thead><tr><th>항목</th><th>시작</th><th>값</th></tr></thead><tbody>{samples.slice(0,50).map((s,i)=><tr key={s.platformId||i}><td>{s.type}</td><td>{s.startDate}</td><td>{s.type==='workouts'?`${s.workoutType} · ${s.duration}초`:`${s.value} ${s.unit}`}</td></tr>)}</tbody></table></div>}</Card><Card title="운동 리마인더"><label>매일 알림 시각 <input type="number" min="0" max="23" value={hour} onChange={e=>setHour(Number(e.target.value))}/></label><div className="motion-controls"><button className="btn btn-primary" disabled={busy} onClick={()=>run(async()=>{const [measurements,routines,workouts]=await Promise.all([HealthAPI.listMeasurements(),HealthAPI.listRoutines(),HealthAPI.listWorkouts()]);await setReminders(true,{measurement:measurements.at(-1),routine:routines[0],workouts,hour});setMessage('기기 알림을 설정했습니다.');})}>로컬 알림 켜기</button><button className="btn btn-ghost" disabled={busy} onClick={()=>run(async()=>{await setReminders(false);setMessage('기기 알림을 해제했습니다.');})}>알림 해제</button><button className="btn btn-ghost" disabled={busy||import.meta.env.VITE_PUSH_CONFIGURED!=='true'} onClick={()=>run(async()=>{await registerPush();setMessage('기기 푸시 등록 완료. 발송 서버는 별도로 연결해야 합니다.');})}>원격 푸시 연결 확인</button></div><p>알림에는 상세 건강수치를 포함하지 않습니다. 실제 발송 시간은 기기 절전·알림 설정에 영향을 받습니다.</p></Card><p role="status">{message}</p></>;}
