import {billingSDKStatus} from '../../shared/lib/subscriptions.js';
import {offlineState} from '../../shared/lib/offline.js';
import {poseDiagnostics} from '../lib/poseDiagnostics.js';
import {rendererStats,rendererModeStats} from '../components/body3d/rendererStats.js';
import React,{useState} from 'react';
import {Capacitor} from '@capacitor/core';
import {healthAvailability} from '../../shared/lib/deviceHealth.js';
import {api} from '../../shared/lib/api.js';
import {useApiData} from '../lib/useApiData.js';
import {Card,ErrorState} from '../../shared/components/ui.jsx';
export default function DiagnosticsPage(){
 const state=useApiData(()=>api('/api/diagnostics'),[]),[checks,setChecks]=useState({}),[busy,setBusy]=useState(false);
 async function inspect(){setBusy(true);const offline=offlineState(),pose=poseDiagnostics();const next={'Device model':'NOT TESTED — native device evidence required','OS':navigator.userAgentData?.platform||navigator.platform,'Build commit':state.data?.build_commit||'NOT SET','Offline database':offline.storageError?'ERROR':offline.ready?'encrypted / ready':'not unlocked','Memory warning':performance.memory?(performance.memory.usedJSHeapSize/performance.memory.jsHeapSizeLimit>.8?'high heap usage':'no heap pressure observed'):'unavailable','Pose inference latency ms':pose?.inferenceMs??'NOT TESTED','Pose FPS':pose?.poseFPS??'NOT TESTED','Camera frame FPS':pose?.cameraFPS??'NOT TESTED','RevenueCat SDK':billingSDKStatus()};const begun=performance.now();try{await api('/api/diagnostics');next['Backend latency ms']=Math.round(performance.now()-begun);}catch{next['Backend latency ms']='unavailable';}for(const [mode,stats] of Object.entries(rendererModeStats()))next['3D '+mode]=stats.renderedFPS==null?'NOT TESTED':stats.renderedFPS+' FPS (observed, not physical evidence)';const renderer=rendererStats();next['3D Renderer']=renderer?'available (last viewed scene)':'3D 화면을 먼저 여세요';next['Average overlay available']=renderer?.overlayAvailable??false;if(renderer){next.WebGL=renderer.webgl;next.Renderer=renderer.renderer;next.FPS=renderer.renderedFPS+' (on-demand sample; not device benchmark)';next['Mesh count']=renderer.meshCount;next.Vertices=renderer.vertices;next['Geometry buffers']=renderer.geometryBuffers;next['Render submission ms']=renderer.renderTimeMs;next['Overlay enabled']=String(renderer.overlayEnabled);next['Fallback active']=String(renderer.fallbackActive);next['Performance target']='30 FPS / critical floor 20 FPS (의료 성능과 무관)';}
 try{const r=await fetch('/pose/pose_landmarker_lite.task',{method:'HEAD'});next.pose=r.ok?'asset_available_not_inference_verified':'asset_unavailable';}catch{next.pose='unavailable';}
 if(Capacitor.isNativePlatform()){
  try{const {Device}=await import('@capacitor/device');const info=await Device.getInfo();next['Device model']=info.model;next.OS=`${info.operatingSystem} ${info.osVersion}`;}catch{next['Device model']='unavailable';}

  try{const {App}=await import('@capacitor/app');const info=await App.getInfo();next.version=`${info.version} (${info.build})`;}catch{next.version='unavailable';}
  try{const {LocalNotifications}=await import('@capacitor/local-notifications');next.notifications=(await LocalNotifications.checkPermissions()).display;}catch{next.notifications='unavailable';}
 }else{next.version='web';try{next.notifications=Notification.permission;}catch{next.notifications='unsupported';}}
 try{const health=await healthAvailability();next.health=`${health.provider}: ${health.available?'available_permission_not_verified':'unavailable'}`;}catch{next.health='unavailable';}setChecks(next);setBusy(false);}
 return <Card title="기기 진단 · QA"><p>권한을 자동 요청하지 않습니다. 아래 상태는 실제 기기 인증이나 스토어 승인 결과가 아닙니다.</p>{state.error&&<ErrorState message={state.error.message} onRetry={state.reload}/>}{state.data?.release&&<section><h3>Pilot readiness · {state.data.release.pilot_ready?'VERIFIED':'EXTERNAL SETUP REQUIRED'}</h3><p>{state.data.release.notice}</p><dl>{Object.entries(state.data.release.checks).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section>}<dl>{Object.entries({platform:Capacitor.getPlatform(),camera:navigator.mediaDevices?.getUserMedia?'api_available_permission_not_checked':'unavailable',api:state.data?.api||'checking',auth:state.data?.auth||'unknown',database:state.data?.database||'unknown',billing:state.data?.billing||'unknown',school:state.data?.school?.integration_status||'unknown',...checks}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><button className="btn btn-primary" disabled={busy} onClick={inspect}>{busy?'확인 중…':'기기 상태 확인'}</button></Card>;
}
