import {clearWorkoutDrafts,clearOffline,clearResponseCache,bindOfflineAccount,offlineState} from '../../shared/lib/offline.js';
import {clearLocalAccount} from '../../shared/lib/accountLifecycle.js';
import React,{useState} from 'react';
import {api,BASE} from '../../shared/lib/api.js';
import {useApiData} from '../lib/useApiData.js';
import {Card,ErrorState} from '../../shared/components/ui.jsx';
export default function PrivacyPage(){const exportData=useApiData(()=>api('/api/privacy/export'),[]),[confirmation,setConfirmation]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
async function run(path,body,method='DELETE'){
 setBusy(true);
 try{
  const fullDelete=path.endsWith('/account')||path.endsWith('/health-data');
  if(method==='DELETE'&&!fullDelete&&(offlineState().pending||offlineState().drafts)){setMessage('미전송 기록을 전송하거나 삭제하고, 진행 중 임시 입력도 정리한 뒤 삭제하세요.');return;}
  const r=await api(path,body,{method});clearResponseCache();setMessage(r.notice||'처리되었습니다.');
  if(path.endsWith('/account')){await clearLocalAccount();location.replace('/health');}
  else {if(fullDelete){await clearOffline();await bindOfflineAccount(exportData.data.profile.id,BASE);}await exportData.reload();}
 }catch(e){setMessage(e.message);}finally{setBusy(false);}
}
async function download(){try{const data=await api('/api/privacy/export'),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='synex-my-health-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setMessage(e.message);}}
return <><Card title="개인정보와 공유 관리"><p>내 기록을 내려받거나 공유를 철회할 수 있습니다.</p>{exportData.error&&<ErrorState message={exportData.error.message}/>}<button className="btn btn-primary" onClick={download}>내 데이터 내보내기</button><button className="btn btn-ghost" disabled={busy||!exportData.data} onClick={()=>run('/api/health/school',{school_id:exportData.data?.profile?.school_id,share_with_center:false},'PUT')}>건강센터 공유 철회</button><h3>공유 동의 이력</h3>{(exportData.data?.sharing_history||[]).map(h=><p key={h.id}>{h.created_at.slice(0,16)} · {h.school_id||'학교 없음'} · {h.shared?'동의':'철회'}</p>)}</Card><Card title="진행 중 임시 입력"><p>아직 서버에 운동 기록으로 저장하지 않은 입력입니다. 전체 삭제해도 이미 저장했거나 전송 대기 중인 운동 기록은 유지됩니다.</p><button className="btn btn-ghost" disabled={busy} onClick={async()=>{if(!window.confirm('이 기기의 진행 중 임시 입력을 모두 삭제할까요?'))return;setBusy(true);try{await clearWorkoutDrafts();setMessage('진행 중 임시 입력을 삭제했습니다.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}}>진행 중 임시 입력 모두 삭제</button></Card><Card title="기록별 삭제"><p>측정 삭제 시 비교값이 남지 않도록 모든 파생 분석·루틴을 초기화합니다. 직접 기록한 운동 내역은 루틴 연결을 해제하고 유지합니다.</p>{(exportData.data?.measurements||[]).map(m=><p key={m.id}>{m.measurement_date} <button className="btn btn-ghost" disabled={busy} onClick={()=>{if(window.confirm('이 측정과 파생 기록을 삭제할까요?'))run(`/api/body-composition/${m.id}`);}}>측정 삭제</button></p>)}{(exportData.data?.workouts||[]).map(w=><p key={w.id}>{w.date} {w.exercise_name} <button className="btn btn-ghost" disabled={busy} onClick={()=>{if(window.confirm('이 운동 기록을 삭제할까요?'))run(`/api/workouts/${w.id}`);}}>운동 삭제</button></p>)}</Card><Card title="전체 삭제"><p>전체 삭제 시 기기에 보관된 미전송 기록도 삭제되며 복구할 수 없습니다. 계정 삭제는 외부 학교 계정이나 Apple/Google 구독을 자동 해지하지 않습니다.</p><label>확인 문구 DELETE 입력<input value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><div className="motion-controls"><button className="btn btn-ghost" disabled={busy||confirmation!=='DELETE'} onClick={()=>run('/api/privacy/health-data',{confirmation})}>건강 데이터 전체 삭제</button><button className="btn btn-ghost" disabled={busy||confirmation!=='DELETE'} onClick={()=>run('/api/privacy/account',{confirmation})}>계정 삭제</button></div><p role="status">{message}</p></Card></>;}
