"""SQLAlchemy transaction/connection adapter preserving the repository's parameterized SQL.
SQLite stays the development default. PostgreSQL uses dialect upserts, not REPLACE.
Only trusted internal SQL is accepted; values are always bound parameters.
"""
import re
from contextlib import contextmanager
from sqlalchemy import create_engine,inspect,text,MetaData,Table
from sqlalchemy.dialects.postgresql import insert

class Rows:
    def __init__(self,rows):self.rows=rows
    def __iter__(self):return iter(self.rows)
    def fetchall(self):return self.rows
    def fetchone(self):return self.rows[0] if self.rows else None

class Connection:
    def __init__(self,connection):self.connection=connection
    def execute(self,sql,values=()):
        if sql.startswith('PRAGMA journal_mode'):return Rows([])
        pragma=re.match(r'PRAGMA table_info\((\w+)\)',sql)
        if pragma:return Rows([(i,c['name']) for i,c in enumerate(inspect(self.connection).get_columns(pragma[1]))])
        upsert=re.match(r'INSERT OR (REPLACE|IGNORE) INTO (\w+)\s*(\([^)]*\))?\s*VALUES',sql,re.I)
        if upsert:
            table=Table(upsert[2],MetaData(),autoload_with=self.connection)
            columns=[c.strip() for c in upsert[3][1:-1].split(',')] if upsert[3] else [c.name for c in table.columns]
            stmt=insert(table).values(**dict(zip(columns,values)))
            keys=[c.name for c in table.primary_key.columns]
            if upsert[1]=='IGNORE':stmt=stmt.on_conflict_do_nothing()
            else:stmt=stmt.on_conflict_do_update(index_elements=keys,set_={c:stmt.excluded[c] for c in columns if c not in keys})
            return self.connection.execute(stmt)
        sql=sql.replace('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        pieces=sql.split('?')
        if len(pieces)-1!=len(values):raise ValueError('Parameter count mismatch')
        bound=pieces[0]+''.join(f':p{i}'+piece for i,piece in enumerate(pieces[1:]))
        return self.connection.execute(text(bound),{f'p{i}':v for i,v in enumerate(values)})

class Database:
    def __init__(self,url,schema=None):
        if not url.startswith('postgresql+psycopg://'):raise ValueError('DATABASE_URL must use postgresql+psycopg://')
        self.schema=schema
        if schema and schema not in ('health_auth','health_audit'):raise ValueError('Unknown schema')
        self.engine=create_engine(url,pool_pre_ping=True,pool_size=5,max_overflow=5,hide_parameters=True)
    @contextmanager
    def connect(self):
        with self.engine.begin() as connection:
            if self.schema:
                connection.execute(text(f'CREATE SCHEMA IF NOT EXISTS {self.schema}'))
                connection.execute(text(f'SET LOCAL search_path TO {self.schema}'))
            yield Connection(connection)
