import {test,expect} from '@playwright/test';
async function confirmAction(page,accept,action){
 const handled=new Promise((resolve,reject)=>page.once('dialog',dialog=>(accept?dialog.accept():dialog.dismiss()).then(resolve,reject)));
 await Promise.all([handled,action()]);
}
test.use({timezoneId:'Asia/Seoul',viewport:{width:390,height:844}});
test('encrypted draft survives closed page and guards app navigation before resuming in Korean timezone',async({page,context},info)=>{
 await context.addInitScript(()=>localStorage.setItem('synex-onboarding-v1','done'));
 await page.goto('/health/workout');
 for(const w of await(await page.request.get('/api/workouts')).json())await page.request.delete(`/api/workouts/${w.id}`);
 const generated=await page.request.post('/api/exercise-routines/generate',{data:{}});expect(generated.ok()).toBeTruthy();const routine=await generated.json();
 await page.reload();const card=page.locator('.exercise-card').filter({has:page.getByRole('button',{name:'세트 추가',exact:true})}).first();
 await card.getByRole('button',{name:'세트 추가',exact:true}).click();await card.getByLabel('1세트 중량 kg',{exact:true}).fill('18');await card.getByLabel('1세트 횟수',{exact:true}).fill('7');
 await expect(card.getByText('기기에 임시 저장됨',{exact:true})).toBeVisible();
 await confirmAction(page,false,()=>page.locator('.health-bottom-nav a[href="/health/profile"]').click());await expect(page).toHaveURL(/\/health\/workout$/);
 await confirmAction(page,true,()=>page.locator('.health-bottom-nav a[href="/health/profile"]').click());await expect(page).toHaveURL(/\/health\/profile$/);
 await page.goBack();await expect(page.getByLabel('1세트 중량 kg',{exact:true})).toHaveValue('18');
 await page.close();page=await context.newPage();await page.goto('/health/workout');await expect(page.getByLabel('1세트 횟수',{exact:true})).toHaveValue('7');
 const restored=page.locator('.exercise-card').filter({has:page.getByLabel('1세트 중량 kg',{exact:true})});
 await confirmAction(page,true,()=>restored.getByRole('button',{name:'임시 입력 버리기',exact:true}).click());
 await page.getByRole('button',{name:'운동 따라하기 · 한 운동씩 시작',exact:true}).click();
 await page.getByLabel('이번 세트 반복 횟수',{exact:true}).fill('9');await page.getByLabel('이번 세트 중량 kg',{exact:true}).fill('21');await page.getByRole('button',{name:'세트 완료',exact:true}).click();
 await expect(page.getByText('기기에 임시 저장됨',{exact:true})).toBeVisible();await page.close();page=await context.newPage();await page.goto('/health/workout');await page.getByRole('button',{name:'운동 따라하기 · 한 운동씩 시작',exact:true}).click();
 await expect(page.getByRole('button',{name:'운동 계속하기',exact:true})).toBeVisible();await expect(page.getByLabel('1세트 중량 kg',{exact:true})).toHaveValue('21');
 await page.getByRole('button',{name:'운동 계속하기',exact:true}).click();await page.getByRole('button',{name:'완료 기록 · 다음 운동',exact:true}).click();
 await expect(page.getByRole('heading',{name:/운동 따라하기 · 2/})).toBeVisible();
 const logs=await(await page.request.get('/api/workouts')).json();const saved=logs.filter(w=>w.routine_id===routine.id);expect(saved).toHaveLength(1);expect(saved[0]).toMatchObject({time_zone:'Asia/Seoul',completion_status:'completed',set_records:[{weight_kg:21,reps:9,kind:'working'}]});
 await page.screenshot({path:info.outputPath('draft-resumed.png'),fullPage:true});
});
test('mobile workout menu, unsaved safety answers, and archived routine draft recovery',async({page,context})=>{
 await context.addInitScript(()=>localStorage.setItem('synex-onboarding-v1','done'));
 await page.goto('/health/profile');
 const safety=page.getByLabel('최근 심한 흉통이 있었나요?',{exact:true});await expect(safety).toBeVisible();const original=await safety.isChecked();await safety.setChecked(!original);
 const workoutLink=page.locator('.health-bottom-nav a[href="/health/workout"]');await expect(workoutLink).toBeVisible();
 await confirmAction(page,false,()=>workoutLink.click());await expect(safety).toBeChecked({checked:!original});
 await confirmAction(page,true,()=>workoutLink.click());await expect(page).toHaveURL(/\/health\/workout$/);await expect(page.getByRole('heading',{name:'내 속도로, 하나씩',exact:true})).toBeVisible();
 await page.locator('.health-bottom-nav a[href="/health/profile"]').click();await expect(safety).toBeChecked({checked:original});
 const first=await page.request.post('/api/exercise-routines/generate',{data:{}});expect(first.ok()).toBeTruthy();const old=await first.json();
 await page.locator('.health-bottom-nav a[href="/health/workout"]').click();
 const card=page.locator('.exercise-card').filter({has:page.getByRole('button',{name:'세트 추가',exact:true})}).first();
 await card.getByRole('button',{name:'세트 추가',exact:true}).click();await card.getByLabel('1세트 횟수',{exact:true}).fill('6');await expect(card.getByText('기기에 임시 저장됨',{exact:true})).toBeVisible();
 const newer=await page.request.post('/api/exercise-routines/generate',{data:{}});expect(newer.ok()).toBeTruthy();expect((await newer.json()).id).not.toBe(old.id);
 await confirmAction(page,true,()=>page.getByRole('link',{name:'임시 입력 관리',exact:true}).click());
 const list=page.getByRole('region',{name:'임시 운동 기록 목록'});await expect(list.getByRole('link',{name:'이 기록 이어 쓰기'})).toHaveCount(1);
 await list.getByRole('link',{name:'이 기록 이어 쓰기'}).click();await expect(page).toHaveURL(new RegExp('routine='+old.id));await expect(page.getByLabel('1세트 횟수',{exact:true})).toHaveValue('6');
});
test('partial profile save is explained and local draft stays readable during routine server failure',async({page,context})=>{
 await context.addInitScript(()=>localStorage.setItem('synex-onboarding-v1','done'));
 await page.goto('/health/profile');const height=page.locator('#height-input');await expect(height).toBeVisible();const original=await height.inputValue(),changed=original==='180'?'181':'180';await height.fill(changed);
 let fail=true;await page.route('**/api/exercise-profile',async route=>{if(route.request().method()==='PUT'&&fail){fail=false;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'test interruption'})});}else await route.continue();});
 await page.getByRole('button',{name:'저장하기',exact:true}).click();await expect(page.getByText(/키·성별은 저장되었습니다/)).toBeVisible();await expect(height).toHaveValue(changed);
 expect((await(await page.request.get('/api/health/profile')).json()).height).toBe(Number(changed));
 await page.getByRole('button',{name:'저장하기',exact:true}).click();await expect(page.getByText('저장되었습니다.',{exact:true})).toBeVisible();await expect(height).toBeEnabled();
 const generated=await page.request.post('/api/exercise-routines/generate',{data:{}});expect(generated.ok()).toBeTruthy();
 await page.locator('.health-bottom-nav a[href="/health/workout"]').click();await expect(page.getByRole('heading',{name:'내 속도로, 하나씩',exact:true})).toBeVisible();
 const card=page.locator('.exercise-card').filter({has:page.getByRole('button',{name:'세트 추가',exact:true})}).first();await card.getByRole('button',{name:'세트 추가',exact:true}).click();await card.getByLabel('1세트 횟수',{exact:true}).fill('7');await expect(card.getByText('기기에 임시 저장됨',{exact:true})).toBeVisible();
 await page.route('**/api/exercise-routines',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'plan service unavailable'})}));
 await confirmAction(page,true,()=>page.getByRole('link',{name:'임시 입력 관리',exact:true}).click());
 const list=page.getByRole('region',{name:'임시 운동 기록 목록'});await expect(list.getByRole('alert')).toContainText('기기에 보관된 입력');await list.getByText('보관된 입력 확인',{exact:true}).click();await expect(list.getByText(/1세트:.*7회/)).toBeVisible();await expect(list.getByRole('link',{name:'이 기록 이어 쓰기'})).toHaveCount(0);
});
